version: "2.4"

networks:
  default:

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.Test
    depends_on:
      redis:
        condition: service_healthy
    environment:
      REDIS_HOST: tcp://redis:7000,tcp://redis:7001,tcp://redis:7002
      REDIS_HOST_SLAVE: tcp://redis:7003,tcp://redis:7004,tcp://redis:7005

  redis:
    image: grokzen/redis-cluster:5.0.5
    environment:
      SENTINEL: "false"
      STANDALONE: "false"
    expose:
      - '7000-7007'
      - '5000-5002'
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "7000", "PING"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
